### ISSUE TITLE
timezone setting on program page

### ISSUE THREAD

**Issue by kberry** [TeXUsersGroup/TUG-Conference#14]
I asked Max Chernoff (not sure how to link him here, sorry) if he could implement a way to allow users to set the timezone for display on the program page (of course the system tz remains the default). Several people have asked for that feature, and it would definitely be invaluable when working on creating the schedule.

Max sent back the attached patch. Can you (Paulo) try it? I can't ...

He writes: "I just changed the timezone <span> at the top into an <input>. Let me
know if you want me to move it to the bottom. ... The moment library loaded on the page comes with a list of timezones, so I used that."

[tz.txt](https://github.com/TeXUsersGroup/TUG-Conference/files/9330042/tz.txt)

**Comment by gucci-on-fleek** [comment]
> I asked Max Chernoff (not sure how to link him here, sorry)

You can use @gucci-on-fleek. I found this thread no problem though, so no need to do anything now.
