### ISSUE TITLE
Do not rely on "Break," to recognize a break in the conference

### ISSUE THREAD

**Issue by pauloney** [TeXUsersGroup/TUG-Conference#2]
Right now `make-schedule.js` realies on the string

Break,

yes, with a comma on it, to recognize a break in Coneference schedule as predicted by the DB file "pres.dat".

It would be nicer and more reliable if we could have a definite and clearer string like

Break-in-the-conference

which is more determinitic and not something one can easily mistype. It this was it will be clear the whole string is needed.

**Comment by yoniros** [comment]
Fixed with e59e4ccc71241c210bda7ee26bf8f54dae218b1c
