### ISSUE TITLE
Turn the poshlets on and off

### ISSUE THREAD

**Issue by pauloney** [TeXUsersGroup/TUG-Conference#8]
From Karl:

The LaTeX logo comes out horribly for me (different font sizes no
doubt). "TeX" is no prize either. Do we really have to pretend we can
typeset the logos? Why not just typeset normal letters "LaTeX". Surely
that is more accessible anyway :).

**Comment by pauloney** [comment]
The poshlets are being more and more used in website and printed material. The position of TUG is that they shiuld NOT be used. For now we should make it optional with a button to turn the poshlets on and off and conduct a case study of what people prefer.

**Comment by kberry** [comment]
Paulo asked how the logo comes out for me. attached. the font size is also arbitrarily reduced from what I set in my browser, btw. argh.

![s](https://user-images.githubusercontent.com/362855/184032218-51cb9a54-65c7-4811-aa08-0ccd134f1190.png)

**Comment by pauloney** [comment]
We are closing this now. The latest version has a button to toggle the poshlets on and off, and remembers the last choice and always use it upon reload.

**Comment by pauloney** [comment]
Closing as uploaded.
