### ISSUE TITLE
Minimize information and duplicity inside pres.dat

### ISSUE THREAD

**Issue by pauloney** [TeXUsersGroup/TUG-Conference#9]
Karl asks us to have a minimal of information on 

        pres.dat

including not writing full path to Slides, Preprints and other packages offered by speakers.

His proposal is that we deposit the files in an `assets` directory, following the talk-tag, for example

         cereda-silly-Slides.pdf

and then the offerring of the file for download would properly write the full name for the file

        Paulo-Cereda-TUG2022-Slides-silly.pdf

based on either `author` entry or `authorascii` if that exists.

**Comment by kberry** [comment]
yes. the fundamental idea is to have only original/source information in pres.dat (or tlk.dat or whatever name it has this year),  not redundant information that can be computed. Because then inevitably conflicts will arise.

**Comment by pauloney** [comment]
Karl, we are discussing things here....and have one question. 

Would you favor just dropping the files -- named with the tag and a termination -- in an specific directory, something like

      cereda-silly-Slides-1.pdf


Or, to also -- forcebly -- list it on the pres.dat file?

We could scan the directory for the files with specified names and either rename them in a new dir or serve it directly from within JavaScript.

The only problem with the solution is that files with the specific names should not be left laying around in the directory.

**Comment by kberry** [comment]
I'm sorry, I don't understand what you're proposing. As faras the filename goes, I'm fine with cereda-silly-Slides-1.pdf (though I don't see the need for the -1), but I thought you didn't like that, and wanted the full name and "TUG2022" in there. Which is also ok with me.

My general idea about pres.dat is that, whatever the convention of the Slides/etc. filename generation, it should be automatically derivable from the data already present in pres.dat (which I called tlk.dat, but anyway). Therefore it is asking for inconsistencies to arise if you list all the files explicitly.

**Comment by pauloney** [comment]
In this way we will avoid all duplicity and not even write the file names
to the DB.

PN

**Comment by kberry** [comment]
In this way we will avoid all duplicity and not even write the file
    names to the DB.

That is exactly the goal I desire :).

**Comment by pauloney** [comment]
Cool.

PN

**Comment by pauloney** [comment]
This is implemented in the newest version, so closing it now.

**Comment by pauloney** [comment]
What I am proposing is to:

1- Populate the directory with files named

       tag-category-number.termination

Like, for example:

         cereda-silly-Slides-1.pdf

The number -- may -- be required because some authors have more than one
file in the same category: two sets of slides....


2- Leave the directory free of similarly named files that do NOT belong to
the set.

3- Do not write anything to the database on the issue of file download.

We will scan the directory and build the HTML and serve the files with the
long (served name), with everything.

Paulo Ney

**Comment by kberry** [comment]
What I am proposing is to:

All that sounds fine to me. At the end, you have:

    We will scan the directory and build the HTML and serve the files
    with the long (served name), with everything.

And would this "serving" work?

As long as we don't have to make a second copy of all the files with the
long/served name, it's fine with me. Symlinks would work, I imagine.

If you were thinking to download via a script that "translates" the names
(to prepend the "TUG2022" or whatever), well, I have no overwhelming
objection, but I think having the files named as needed in the first
place is a lot simpler. Every script is another attack vector.

Thanks,
Karl
